/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const SignedoutLazyImport = createFileRoute('/signedout')()
const SignedinLazyImport = createFileRoute('/signedin')()
const CanvasLazyImport = createFileRoute('/canvas')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const SignedoutLazyRoute = SignedoutLazyImport.update({
  path: '/signedout',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/signedout.lazy').then((d) => d.Route))

const SignedinLazyRoute = SignedinLazyImport.update({
  path: '/signedin',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/signedin.lazy').then((d) => d.Route))

const CanvasLazyRoute = CanvasLazyImport.update({
  path: '/canvas',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/canvas.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/canvas': {
      preLoaderRoute: typeof CanvasLazyImport
      parentRoute: typeof rootRoute
    }
    '/signedin': {
      preLoaderRoute: typeof SignedinLazyImport
      parentRoute: typeof rootRoute
    }
    '/signedout': {
      preLoaderRoute: typeof SignedoutLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  CanvasLazyRoute,
  SignedinLazyRoute,
  SignedoutLazyRoute,
])

/* prettier-ignore-end */
